### ISSUE TITLE
打包后，静态资源加载失败

### ISSUE THREAD

**Issue by HaiDongQingYu** [pure-admin/electron-pure-admin#3]
![image](https://user-images.githubusercontent.com/66376469/218673888-eb205fbb-016a-44dc-b1e7-baf704691c30.png)
![image](https://user-images.githubusercontent.com/66376469/218673999-682c565a-f8a5-4733-91c9-5111a62cf6e2.png)

**Comment by xiaoxian521** [comment]
升级 `@pureadmin/theme` 到最新版 平台发布 `4.0.0` 后会统一同步代码

**Comment by xiaoxian521** [comment]
`4.1.0`版本已修复 拉取最新代码
