### ISSUE TITLE
为什么electron打包成.exe文件后运行打不开呢？一直转圈圈

### ISSUE THREAD

**Issue by GitHub1d** [pure-admin/electron-pure-admin#4]

**Comment by xiaoxian521** [comment]
有没有改什么文件呢 如果没有提供下报错截图

**Comment by GitHub1d** [comment]
什么也没改。拉下来后直接 yarn install 然后 打包安装的。








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pure-admin/electron-pure-admin] 为什么electron打包成.exe文件后运行打不开呢？一直转圈圈 (Issue #4)





 
有没有改什么文件呢 如果没有提供下报错截图

**Comment by xiaoxian521** [comment]
提供下报错截图

**Comment by GitHub1d** [comment]
![image](https://user-images.githubusercontent.com/96401368/228454055-6115172a-0731-4aec-8f34-168a482f4058.png)

**Comment by xiaoxian521** [comment]
`4.1.0`版本已修复 拉取最新代码
