### ISSUE TITLE
yarn build electron-builder打包后路径有问题

### ISSUE THREAD

**Issue by wsw2000** [pure-admin/electron-pure-admin#5]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/63382474/232402886-e70ea70b-61f7-439f-9df8-ee86685cbcbb.png">

**Comment by QSpinach** [comment]
![image](https://user-images.githubusercontent.com/22956372/236610796-61edd7a1-8e6e-4f91-8bde-039f3e7f0512.png)

**Comment by xiaoxian521** [comment]
`4.1.0`版本已修复 拉取最新代码

**Comment by GitHub1d** [comment]
这是什么问题
![image](https://github.com/pure-admin/electron-pure-admin/assets/96401368/81da758f-ea28-49e5-a3e8-7e5440b8d6bc)
